# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool: default

steps:
- script: |
    nssm stop wordpressApi
    nssm stop rabbitMqReceiver
    nssm stop heartbeatRabbitMq
  displayName: 'Stopping integration service'

- script: |
    cd C:\Users\admin\Source\Repos\WordpressApi
    git pull origin master
  displayName: 'Updating git repo'

- powershell: |
    cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
    .\msbuild C:\Users\admin\Source\Repos\WordpressApi\WordpressApi\WordpressApi.csproj /p:Configuration=Release
  displayName: 'Installing dependencies'

- script: |
    nssm start wordpressApi
    nssm start rabbitMqReceiver
    nssm start heartbeatRabbitMq
  displayName: 'Starting integration service'

