# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool: default

steps:
- script: |
    nssm stop wordpressApi
    nssm stop rabbitMqReceiver
  displayName: 'Stopping integration service'

- powershell: |
    cd C:\Users\admin\Source\Repos\WordpressApi
    git pull origin master
  displayName: 'Updating Git repository'

- powershell: |
    cd C:\Windows\Microsoft.NET\Framework\v4.0.30319 
    .\msbuild C:\Users\admin\Source\Repos\WordpressApi\WordpressApi\WordpressApi.csproj /p:Configuration=Release
  displayName: 'Installing dependencies'

- script: |
    nssm start wordpressApi
    nssm start rabbitMqReceiver
  displayName: 'Starting integration service'
